-- Generated by PremadeIQ Uploader. Do not edit by hand.
-- Character -> guild, for the guild watchlist; refreshed twice a day.
PremadeIQ_GuildMap = {
  version = 1,
  generated_at = 0,
  guilds = {
  },
  players = {
  },
}
