-- Generated by PremadeIQ Uploader. Do not edit by hand.
-- Refreshed each sync; picked up by the addon on /reload or login.
PremadeIQ_KnownPremades = {
  version = 1,
  generated_at = 0,
  tier = nil,
  leaders = {
  },
}
