-- Generated by PremadeIQ Uploader. Do not edit by hand.
-- Winrates for the in-game odds line; refreshed daily.
PremadeIQ_PlayerStats = {
  version = 1,
  generated_at = 0,
  min_known = 8,
  model = {
    wr = 0.000000,
    new = 0.000000,
    accuracy = 0,
  },
  players = {
  },
}
