#!/usr/bin/env python3
"""Release guard for the public PremadeIQ mirror.

Refuses (exit 1) any source tree or built zip that carries data which must
never ship publicly:

  * KnownPremades.lua that is NOT the neutral stub — i.e. the live catalog
    (markers: tier = "god", generated_at != 0, a non-empty leaders table);
  * UploadState.lua carrying live cursors (installIds);
  * any PremadeIQ_Leader path — the owner-only leader module;
  * any text file referencing removed legacy modules/feature names, or leaking a
    server hostname / raw IPv4 / owner identity (see FORBIDDEN_CONTENT).

This mirrors the hard guard in package_addon.py, but stands alone (no project
imports) so it can run inside the mirror's GitHub Actions, where only the
public tree exists.

Wired into .github/workflows/release.yml twice:

    python tools/check_release.py --tree .          # before BigWigs packager
    python tools/check_release.py --zip .release    # after artifacts are built

The stub below is the single source of truth for byte-for-byte comparison and
must stay identical to what the sync script force-writes into the mirror.
"""
from __future__ import annotations

import argparse
import re
import sys
import zipfile
from pathlib import Path

STUB = (
    "-- Generated by PremadeIQ Uploader. Do not edit by hand.\n"
    "-- Refreshed each sync; picked up by the addon on /reload or login.\n"
    "PremadeIQ_KnownPremades = {\n"
    "  version = 1,\n"
    "  generated_at = 0,\n"
    "  tier = nil,\n"
    "  leaders = {\n"
    "  },\n"
    "}\n"
)

FORBIDDEN_PATH = "PremadeIQ_Leader"
KP_NAME = "KnownPremades.lua"
US_NAME = "UploadState.lua"


def kp_violation(text: str) -> str | None:
    """Return a reason string if KnownPremades content is unsafe, else None.

    Line endings are normalised before the stub comparison: git autocrlf and
    the BigWigs packager can rewrite LF<->CRLF, which is benign. The live-data
    checks below stay strict on content, so a real catalog still can't slip by.
    """
    if text.replace("\r\n", "\n").replace("\r", "\n") == STUB:
        return None
    # Not the stub — pin down WHY for a useful CI error.
    if re.search(r'tier\s*=\s*"[^"]+"', text):
        return 'live tier marker (tier = "…")'
    if re.search(r"generated_at\s*=\s*(?!0\b)\d+", text):
        return "generated_at != 0"
    if re.search(r"guid\s*=", text):
        return "non-empty leaders (guid entries present)"
    return "not the neutral stub"


def us_violation(text: str) -> str | None:
    """UploadState.lua must ship as the neutral stub, never the owner's live
    cursors — those carry installIds derived from realm + character GUID."""
    if "samplesUploadedThrough" in text:
        return "live upload cursor (samplesUploadedThrough present)"
    return None


# Content that must never ride along in the public addon, in any text file:
#   * names of the removed raid-streaming / consent feature — the 0.9.23 public
#     framing is deliberately neutral, so a leftover reference (in a .lua comment
#     or an old CHANGELOG entry) would re-expose what we chose not to name;
#   * any server hostname / raw IPv4 / owner real-name — the addon carries only
#     game data and must never tie the public artifact to the owner or the box.
FORBIDDEN_CONTENT = (
    (re.compile(r"AceComm", re.I), "AceComm reference (removed module)"),
    (re.compile(r"SendStream", re.I), "SendStream reference (removed module)"),
    (re.compile(r"\bComm\.lua\b", re.I), "Comm.lua reference (removed module)"),
    (re.compile(r"/piqdebug", re.I), "/piqdebug reference (removed command)"),
    (re.compile(r"\bopt[-_]?in\b", re.I), "opt-in reference (removed feature)"),
    (re.compile(r"\bopt[-_]?out\b", re.I), "opt-out reference (removed feature)"),
    (re.compile(r"OptShareData|IsOptedOut|MaybeShowConsent|HasConsent",
                re.I), "removed consent API reference"),
    (re.compile(r"position streaming", re.I),
     "position-streaming reference (removed feature)"),
    (re.compile(r"streamed only within your raid", re.I),
     "raid-streaming reference (removed feature)"),
    (re.compile(r"состояние стримится|лайв-стриминг позиций", re.I),
     "raid-streaming reference (removed feature, ru)"),
    (re.compile(r"duckdns", re.I), "server hostname leak (duckdns)"),
    (re.compile(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"), "IPv4 address leak"),
    (re.compile(r"Kholodilin", re.I), "owner real-name leak"),
)

TEXT_SUFFIXES = (".lua", ".md", ".toc", ".xml", ".txt", ".yml", ".yaml")

# The one address the addon is allowed to name. Until 2026-08-16 the only
# download link it carried pointed at a repository that does not exist, so
# `/piq uploader` answered every player with a 404 — the addon has to be able
# to say where the companion app lives.
#
# Deliberately narrow: the full scheme plus one of two exact paths, with
# whatever trailing anchor or query the page needs. /install is where the
# companion app lives; /go is the short path the addon prints so an arrival
# can be attributed to the game. The lookahead keeps the carve-out to those
# two words — /installer or /goodies would still read as a leak.
# The host on its own, any other path, and a scheme-less mention all still
# fail — the exception exists to ship working links to players, not to
# unlock the hostname.
ALLOWED_URL_RE = re.compile(
    r"https://premadeiq\.duckdns\.org/(?:install|go)"
    r"(?![A-Za-z0-9_-])[^\s\"'<>)]*")


def _is_text(name: str) -> bool:
    return name.lower().endswith(TEXT_SUFFIXES)


def _skip_content(rel: str) -> bool:
    """Vendored libs are upstream (not policed); the guard scripts name the
    forbidden tokens in their own source, so exclude them to avoid self-matches."""
    return (
        rel.startswith("Libs/")
        or "/Libs/" in rel
        or rel.endswith("check_release.py")
        or rel.endswith("package_addon.py")
    )


def content_violation(text: str) -> str | None:
    # Blank out the allowed link first, so the hostname inside it doesn't trip
    # the duckdns rule. Replaced by a space, not by nothing: the IPv4 rule is
    # anchored on \b, and splicing the neighbours together could manufacture a
    # match that was never in the file.
    text = ALLOWED_URL_RE.sub(" ", text)
    for rx, label in FORBIDDEN_CONTENT:
        if rx.search(text):
            return label
    return None


def scan_tree(root: Path) -> list[str]:
    problems: list[str] = []
    for p in sorted(root.rglob("*")):
        rel = p.relative_to(root).as_posix()
        if FORBIDDEN_PATH in rel:
            problems.append(f"forbidden path: {rel}")
            continue
        if not p.is_file():
            continue
        if p.name == KP_NAME:
            why = kp_violation(p.read_text(encoding="utf-8", errors="replace"))
            if why:
                problems.append(f"{rel}: {why}")
        elif p.name == US_NAME:
            why = us_violation(p.read_text(encoding="utf-8", errors="replace"))
            if why:
                problems.append(f"{rel}: {why}")
        elif _is_text(p.name) and not _skip_content(rel):
            why = content_violation(p.read_text(encoding="utf-8", errors="replace"))
            if why:
                problems.append(f"{rel}: {why}")
    return problems


def scan_zip(z: Path) -> list[str]:
    problems: list[str] = []
    with zipfile.ZipFile(z) as zf:
        for name in zf.namelist():
            if FORBIDDEN_PATH in name:
                problems.append(f"{z.name}: forbidden path: {name}")
                continue
            base = name.rsplit("/", 1)[-1]
            if base == KP_NAME:
                why = kp_violation(zf.read(name).decode("utf-8", errors="replace"))
                if why:
                    problems.append(f"{z.name}!{name}: {why}")
            elif base == US_NAME:
                why = us_violation(zf.read(name).decode("utf-8", errors="replace"))
                if why:
                    problems.append(f"{z.name}!{name}: {why}")
            elif _is_text(base) and not _skip_content(name):
                why = content_violation(zf.read(name).decode("utf-8", errors="replace"))
                if why:
                    problems.append(f"{z.name}!{name}: {why}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    grp = ap.add_mutually_exclusive_group(required=True)
    grp.add_argument("--tree", metavar="DIR", help="scan a source tree")
    grp.add_argument("--zip", metavar="DIR|FILE", help="scan built zip(s)")
    args = ap.parse_args()

    problems: list[str] = []
    if args.tree:
        root = Path(args.tree)
        if not root.is_dir():
            print(f"!! not a directory: {root}", file=sys.stderr)
            return 2
        problems = scan_tree(root)
    else:
        target = Path(args.zip)
        zips = [target] if target.is_file() else sorted(target.glob("*.zip"))
        if not zips:
            print(f"!! no zip found under {target}", file=sys.stderr)
            return 2
        for z in zips:
            problems += scan_zip(z)

    if problems:
        print("RELEASE GUARD FAILED — refusing to publish:", file=sys.stderr)
        for pr in problems:
            print(f"  - {pr}", file=sys.stderr)
        return 1

    where = args.tree or args.zip
    print(f"release guard: clean ({where})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
